// ============================================
// 构建脚本：将 admin/index.html 打包为 Worker 可导入的 JS 字符串
// 用法：node scripts/build-admin.js
// 生成：workers/src/admin-html.js
// ============================================

const fs = require('fs');
const path = require('path');

const srcPath = path.join(__dirname, '..', 'admin', 'index.html');
const outPath = path.join(__dirname, '..', 'workers', 'src', 'admin-html.js');

let html = fs.readFileSync(srcPath, 'utf-8');

// 转义为安全的 JS 字符串（只处理反引号和反斜杠）
html = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`');

const output = `// Auto-generated by scripts/build-admin.js — do not edit directly
// Source: admin/index.html

const html = \`${html}\`;
export default html;
`;

fs.writeFileSync(outPath, output, 'utf-8');
console.log('Generated: workers/src/admin-html.js (' + output.length + ' bytes)');
